project:
  type: book

book:
  title: "Guida alla psicometria e statistica per la neuropsicologia clinica e forense"
  subtitle: "Elementi per la pratica clinica in psicologia"
  author: "Giorgio Arcara"
  date: "2025-08-03"
  search: true
  repo-url: "https://github.com/giorgioarcara/guida-psicometria-pratica-clinica"
  repo-actions: [edit]
  sharing: [twitter, facebook]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - chapters/nix_nixpkgs.qmd
    - chapters/nix_actions.qmd
    - chapters/conclusion.qmd
  page-navigation: true

bibliography: references.bib

format:
  epub:
    toc:
      true
    lang:
      en-GB
    date:
      "2023-10-19"
    css:
      epub.css
  html:
    include-in-header:
      file: header.html
    theme:
      light: flatly
      dark: solar
    css:
      epub.css
  pdf:
    keep-tex: true
    documentclass: scrbook
    classoption: [paper=6in:9in,pagesize=pdftex,headinclude=on,footinclude=on,12pt]
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \areaset[0.50in]{4.5in}{8in}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
           showspaces = false,
           showtabs = false,
           breaksymbolleft={},
           breaklines
           % Note: setting commandchars=\\\{\} here will cause an error 
        }  
    fig-pos: 'H'
